<?php

$prefix = 'vxras_options';
$img = '/wp-content/themes/vxras/img/';
    CSF::createSection($prefix, array(
        'id'    => 'nav',
        'title' => '导航美化',
        'icon'  => 'fa fa-tasks',
    ));
       CSF::createSection($prefix, array(
        'parent'      => 'nav',
        'title'       => 'LOGO滤镜',
        'icon'        => 'fa fa-spinner',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
            array(
                'style'   => 'warning',
                'type'    => 'submessage',
                'content'    => '基础美化功能提取自MJ美化插件，感谢MJ团队的开发，现由李初一集成美化并做出优化修改',
            ), 
             array(
                'title'   => 'logo扫光',
                'label'   => '让你的网站logo焕然一新！',
                'id'      => 'logoflash',
                'default' => false,
                'type'    => 'switcher',
            ),
              array(
                'title'   => 'hue-rotate 色相动画',
                'label'   => '网站LOGO将会进行动态色彩渐变',
                'id'      => 'logo1',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => 'invert 反色',
                'label'   => '网站LOGO的色彩将进行反色处理，可以看效果喔~',
                'id'      => 'logo2',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => 'drop-shadow 阴影',
                'label'   => '网站LOGO将会被添加一个克莱因蓝色柔光背景',
                'id'      => 'logo3',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => ' ',
                'desc'    =>'选择一个你自己喜欢的颜色',
                'dependency' => array('logo3', '!=', ''),
                'id'       => 'logo3_color',
                'default' => '#ff3e92',
                'type'    => 'color',
            ),
      ),));
       CSF::createSection($prefix, array(
        'parent'      => 'nav',
        'title'       => '导航栏内容',
        'icon'        => 'fa fa-bar-chart',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
            array(
                'title'   => '导航字体加粗',
                'label'   => '让你的导航栏更加醒目！',
                'id'      => 'navbarb',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '标题样式美化',
                'label'   => '导航栏标题将简化主题自带的标题hover效果',
                'id'      => 'navbiaoti',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '禁用搜索功能',
                'label'   => '禁用导航栏顶部的搜索功能',
                'id'      => 'nosearch',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => 'FPS帧率显示',
                'label'   => '网站LOGO左侧显示一个实时的FPS帧率',
                'id'      => 'FPS',
                'default' => false,
                'type'    => 'switcher',
            ),
       ),));
       
       CSF::createSection($prefix, array(
        'parent'      => 'nav',
        'title'       => '导航栏背景',
        'icon'        => 'fa fa-yelp',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
             array(
                'title'   => ' ',
                'label'   => '【童年飞机】',
                'id'      => 'navbg1',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => ' ',
                'label'   => '【紫色薰衣】',
                'id'      => 'navbg2',
                'class'    =>'compact',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => ' ',
                'label'   => '【三生桃花】',
                'id'      => 'navbg3',
                'class'    =>'compact',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => ' ',
                'label'   => '【万里山河】',
                'id'      => 'navbg4',
                'class'    =>'compact',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => ' ',
                'label'   => '【环游动漫】',
                'id'      => 'navbg5',
                'class'    =>'compact',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => ' ',
                'label'   => '【浪漫爱心】',
                'id'      => 'navbg6',
                'class'    =>'compact',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => ' ',
                'label'   => '【蜜桔海滩】',
                'id'      => 'navbg7',
                'class'    =>'compact',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '自定义导航栏皮肤',
                'label'   => '开启后可自定义导航栏皮肤',
                'id'      => 'usernavbg8',
                'type'    => 'switcher',
            ),
             array(
                'title'   => ' ',
                'desc'    =>'请上传自定义导航栏背景图片或填写图片地址，注意尺寸为：1800px*80px',
                'dependency' => array('usernavbg8', '!=', ''),
                'id'       => 'usernavbg88',
                'class'    =>'compact',
                'default' => false,
                'preview' => true,
                'library' => 'image', 
                'type'    => 'upload',
            ),
       ),));
    CSF::createSection($prefix, array(
        'id'    => 'all',
        'title' => '全局美化',
        'icon'  => 'fa fa-codepen',
    ));
     CSF::createSection($prefix, array(
        'parent'      => 'all',
        'title'       => '鼠标特效',
        'icon'        => 'fa fa-hand-pointer-o',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
              array(
                'title'   => '点击五彩斑斓爆炸特效',
                'label'   => '点击鼠标会出现五彩斑斓的爆炸特效',
                'id'      => 'baozha',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '点击搞笑文字特效特效',
                'label'   => '点击鼠标会出现文字显示特效',
                'id'      => 'baozha1',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '点击社会主义核心价值观',
                'label'   => '点击鼠标会随机出现社会主义价值观词语，彰显爱国情操！',
                'id'      => 'aiguo_shehuizhuyihexinjiazhiguan',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '点击彩色粒子特效',
                'label'   => '点击鼠标会出现彩色粒子溅落特效！',
                'id'      => 'aiguo_shehuizhuyihexinjiazhiguan1',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '鼠标跟随光圈（蓝色）',
                'label'   => '启用后，将会有一个蓝色的鼠标光圈实时跟随鼠标移动',
                'id'      => 'mouse_cursor',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '鼠标跟随光圈（绿色）',
                'label'   => '启用后，将会有一个绿色的鼠标光圈实时跟随鼠标移动',
                'id'      => 'mouse_cursor2',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '鼠标跟随光圈（粉色）',
                'label'   => '启用后，将会有一个粉色的鼠标光圈实时跟随鼠标移动',
                'id'      => 'mouse_cursor3',
                'default' => false,
                'type'    => 'switcher',
            ),
              array(
                'title'   => '鼠标右键菜单',
                'label'   => '启用后，将呈现个性化的右键菜单，请自定义菜单栏中最后一个的内容',
                'id'      => 'noft2',
                'default' => false,
                'type'    => 'switcher',
            ),
              array(
                'title'   => ' ',
                'dependency' => array('noft2', '!=', ''),
                'desc'   => '请填写鼠标右键菜单栏内容名称',
                'id'      => 'noft3',
                'class'    =>'compact',
                'default' => false,
                'type'    => 'text',
            ),
             array(
                'title'   => ' ',
                'dependency' => array('noft2', '!=', ''),
                'desc'   => '请填写鼠标右键菜单栏内容链接',
                'id'      => 'noft4',
                'class'    =>'compact',
                'default' => false,
                'type'    => 'text',
            ),
      ),));
      CSF::createSection($prefix, array(
        'parent'      => 'all',
        'title'       => '鼠标皮肤',
        'icon'        => 'fa fa-hand-pointer-o',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
             array(
                'title'   => ' ',
                'desc'    => '<br><img src="'.$img.'shubiao1.png" class="shubiao"><img src="'.$img.'shubiao2.png" class="shubiao">',
                'label'   => '【蓝色精灵】',
                'id'      => 'shubiao',
                'type'    => 'switcher',
                'default' => false,
            ),
             array(
                'title'   => ' ',
                'label'   => '【寒雨剑锋】',
                'desc'    => '<br><img src="'.$img.'arr1.png" class="shubiao"><img src="'.$img.'arr2.png" class="shubiao">',
                'id'      => 'shubiao2',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => ' ',
                'desc'    => '<br><img src="'.$img.'arr3.png" class="shubiao"><img src="'.$img.'arr4.png" class="shubiao">',
                'label'   => '【幽灵琥珀】',
                'id'      => 'shubiao3',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => ' ',
                'desc'    => '<br><img src="'.$img.'arr5.png" class="shubiao"><img src="'.$img.'arr6.png" class="shubiao">',
                'label'   => '【红蓝对决】',
                'id'      => 'shubiao4',
                'class'    =>'compact',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => ' ',
                'desc'    => '<br><img src="'.$img.'arr7.png" class="shubiao"><img src="'.$img.'arr8.png" class="shubiao">',
                'label'   => '【返璞风筝】',
                'id'      => 'shubiao5',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => ' ',
                'desc'    => '<br><img src="'.$img.'arr9.png" class="shubiao"><img src="'.$img.'arr10.png" class="shubiao">',
                'label'   => '【翠色猫石】',
                'id'      => 'shubiao6',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => ' ',
                'label'   => '【黑白无常】',
                'desc'    => '<br><img src="'.$img.'arr11.png" class="shubiao"><img src="'.$img.'arr12.png" class="shubiao">',
                'id'      => 'shubiao7',
                'default' => false,
                'type'    => 'switcher',
            ),
             
      ),));
      
      CSF::createSection($prefix, array(
        'parent'      => 'all',
        'title'       => '动态背景',
        'icon'        => 'fa fa-life-ring',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
            array(
                'title'   => ' ',
                'label'   => '【彩色飘带】',
                'id'      => 'dongtai5',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => ' ',
                'label'   => '【五彩斑斓】',
                'id'      => 'dongtai1',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => ' ',
                'label'   => '【符号元素】',
                'id'      => 'dongtai3',
                'default' => false,
                'type'    => 'switcher',
            ), 
            array(
                'title'   => ' ',
                'label'   => '【粒子连线】',
                'id'      => 'Snowfall2',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => ' ',
                'label'   => '【简约图形】',
                'id'      => 'Snowfall3',
                'default' => false,
                'type'    => 'switcher',
            ),
      ),));
      
        CSF::createSection($prefix, array(
        'parent'      => 'all',
        'title'       => '手机背景',
        'icon'        => 'fa fa-android',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
            array(
                'title'   => '【淡蓝遐想】',
                'label'   => '一个不错的日间手机背景',
                'id'      => 'body_backgroundtu4',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '【熏衣彩云】',
                'label'   => '一个不错的日间手机背景',
                'id'      => 'body_backgroundtu5',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '【遨游题海】',
                'label'   => '一个不错的日间手机背景',
                'id'      => 'body_backgroundtu6',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '【末日审判】',
                'label'   => '一个不错的夜间手机背景',
                'id'      => 'body_backgroundtu6d',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '自定义日间手机背景',
                'label'   => '开启后可自定义日间手机背景',
                'id'      => 'body_backgroundtu66',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => ' ',
                'desc'    =>'请上传自定义手机背景图片或填写图片地址',
                'dependency' => array('body_backgroundtu66', '!=', ''),
                'id'      => 'body_backgroundtu666',
                'class'    =>'compact',
                'default' => false,
                'type'    => 'switcher',
                'preview' => true,
                'library' => 'image', 
                'type' => 'upload',
            ),
            array(
                'title'   => '自定义夜间手机背景',
                'label'   => '开启后可自定义夜间手机背景',
                'id'      => 'body_backgroundtu66d',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => ' ',
                'desc'    =>'请上传自定义手机背景图片或填写图片地址',
                'dependency' => array('body_backgroundtu66d', '!=', ''),
                'id'      => 'body_backgroundtu666d',
                'class'    =>'compact',
                'default' => false,
                'type'    => 'switcher',
                'preview' => true,
                'library' => 'image', 
                'type' => 'upload',
            ),
      ),));
      
      CSF::createSection($prefix, array(
        'parent'      => 'all',
        'title'       => '侧边背景',
        'icon'        => 'fa fa-picture-o',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
             array(
                'title'   => '【淡蓝遐想】',
                'label'   => '一个不错的侧边栏背景',
                'id'      => 'shoujicebianlan1',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '【熏衣彩云】',
                'label'   => '一个不错的侧边栏背景',
                'id'      => 'shoujicebianlan2',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '【遨游题海】',
                'label'   => '一个不错的侧边栏背景',
                'id'      => 'shoujicebianlan3',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '自定义侧边栏背景',
                'label'   => ' ',
                'id'      => 'shoujicebianlan33',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => ' ',
                'dependency' => array('shoujicebianlan33', '!=', ''),
                'id'      => 'shoujicebianlan333',
                'desc'    => '请上传自定义手机侧边栏背景图片或填写图片地址',
                'preview' => true,
                'class'    =>'compact',
                'library' => 'image', 
                'type' => 'upload',
            ),
      ),));
      
       CSF::createSection($prefix, array(
        'parent'      => 'all',
        'title'       => '电脑背景',
        'icon'        => 'fa fa-television',
        'description' => '',
        'fields'      => array(
              array(
                'title'   => '【炫彩夜空】',
                'label'   => '一个不错的日间电脑端背景',
                'id'      => 'body_backgroundtu1',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '【淡蓝遐想】',
                'label'   => '一个不错的日间电脑端背景',
                'id'      => 'body_backgroundtu2',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '【遨游题海】',
                'label'   => '一个不错的日间电脑端背景',
                'id'      => 'body_backgroundtu3',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '【末日审判】',
                'label'   => '一个不错的夜间电脑端背景',
                'id'      => 'body_backgroundtu3d',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '自定义日间电脑端背景',
                'label'   => '开启后可自定义日间电脑端背景',
                'id'      => 'body_backgroundtu33',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '自定义夜间电脑端背景',
                'label'   => '开启后可自定义夜间电脑端背景',
                'id'      => 'body_backgroundtu33d',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'dependency' => array('body_backgroundtu33', '!=', ''),
                'title'   => ' ',
                'id'      => 'body_backgroundtu333',
                'class'    =>'compact',
                'default'  =>false,
                'preview' => true,
                'library' => 'image', 
                'type' => 'upload',
                'desc'    =>'请上传自定义电脑背景图片或填写图片地址',
            ),
             array(
                'dependency' => array('body_backgroundtu33d', '!=', ''),
                'title'   => ' ',
                'id'      => 'body_backgroundtu333d',
                'class'    =>'compact',
                'default'  =>false,
                'preview' => true,
                'library' => 'image', 
                'type' => 'upload',
                'desc'    =>'请上传自定义电脑背景图片或填写图片地址',
            ),
      ),));
      
       CSF::createSection($prefix, array(
        'parent'      => 'all',
        'title'       => '飘落特效',
        'icon'        => 'fa fa-snowflake-o',
        'description' => '',
        'fields'      => array(
             array(
                'title'   => '浪漫樱花特效',
                'label'   => '启用后，网站全局显示浪漫的樱花飘落特效',
                'id'      => 'yinghua',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '枫叶飘落特效',
                'label'   => '启用后，网站全局显示枫叶飘落特效',
                'desc'    => '注意：枫叶飘落特效不能和樱花飘落特效一起用喔~',
                'id'      => 'fengye',
                'default' => false,
                'type'    => 'switcher',
            ),
              array(
                'title'   => '雪花飘落特效',
                'label'   => '启用后，网站全局将会显示雪花飘落的特效',
                'id'      => 'Snowfall1',
                'default' => false,
                'type'    => 'switcher',
            ),
               array(
                'title'   => '全局灰色主题',
                'label'   => '启用后，网站全局变灰,适合国家公祭日等纪念日使用',
                'id'      => 'site_gray',
                'default' => false,
                'type'    => 'switcher',
            ),
      ),));
       CSF::createSection($prefix, array(
        'parent'      => 'all',
        'title'       => '网站字体',
        'icon'        => 'fa fa-pencil',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
             array(
                'title'   => '网站字体1',
                'label'   => '一款不错的字体',
                'desc'    => '<br><img src="'.$img.'font1.png" height="40px">',
                'id'      => 'ziti1',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '网站字体2',
                'label'   => '一款不错的字体',
                'desc'    => '<br><img src="'.$img.'font2.png" height="40px">',
                'id'      => 'ziti2',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '网站字体3',
                'label'   => '一款不错的字体',
                'desc'    => '<br><img src="'.$img.'font3.png" height="40px">',
                'id'      => 'ziti3',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '网站字体4',
                'label'   => '一款不错的字体',
                'desc'    => '<br><img src="'.$img.'font4.png" height="40px">',
                'id'      => 'ziti4',
                'default' => false,
                'type'    => 'switcher',
            ), array(
                'title'   => '网站字体5',
                'label'   => '一款不错的字体',
                'desc'    =>'<br><img src="'.$img.'font5.png" height="40px">',
                'id'      => 'ziti5',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '网站字体6',
                'label'   => '一款不错的字体',
                'desc'    => '<br><img src="'.$img.'font6.png" height="40px">',
                'id'      => 'ziti6',
                'default' => false,
                'type'    => 'switcher',
            ), 
             array(
                'title'   => '自定义网站字体',
                'label'   => ' ',
                'id'      => 'ziti66',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => ' ',
                'desc'   => '请填写自定义的网站字体链接地址',
                'dependency' => array('ziti66', '!=', ''),
                'id'      => 'ziti666',
                'class'    =>'compact',
                'default' => false,
                'type'    => 'text',
            ),
      ),));
    CSF::createSection($prefix, array(
        'id'    => 'jubu',
        'title' => '局部美化',
        'icon'  => 'fa fa-object-group',
    ));
    CSF::createSection($prefix, array(
        'parent'      => 'jubu',
        'title'       => '右侧',
        'icon'        => 'fa fa-arrow-circle-right',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
              array(
                'title'   => '纵向彩色滚动条',
                'label'   => '开启后可以美化网站右侧滚动条',
                'id'      => 'colorfulscrollbar',
                'default' => false,
                'type'    => 'switcher',
            ),
              array(
                'title'   => '右侧悬浮按钮栏',
                'label'   => '右侧悬浮按钮美化——欢迎光临',
                'id'      => 'youcexuanfu1',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '右侧悬浮躲猫猫',
                'label'   => '开启后右侧可显示一只黑色猫猫，可以试试效果奥~',
                'id'      => 'youcexuanfu2',
                'default' => false,
                'type'    => 'switcher',
            ),
      ),));
      
       CSF::createSection($prefix, array(
        'parent'      => 'jubu',
        'title'       => '底部',
        'icon'        => 'fa fa-arrow-circle-down',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
            array(
                'title'   => '网站底部波浪',
                'label'   => '开启后可以在网站底部显示一个蓝色波浪',
                'id'      => 'bolang',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '底部二维码滤镜一',
                'label'   => 'hue-rotate 色相旋转',
                'id'      => 'erweima1',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '底部二维码滤镜二',
                'label'   => 'invert 反色',
                'id'      => 'erweima2',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '底部二维码滤镜三',
                'label'   => 'drop-shadow 阴影',
                'id'      => 'erweima3',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '底部收藏本站',
                'label'   => '开启后将在网站底部显示Ctrl+D收藏本站提示',
                'id'      => 'dixian',
                'default' => false,
                'type'    => 'switcher',
            ),
           array(
                'title'   => '网站底部广告',
                'label'   => '开启后可在网站底部显示广告',
                'id'      => 'advertisement',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => ' ',
                'desc'   => '请填写广告链接地址',
                'id'      => 'advertisement1',
                'default' => false,
                'type'    => 'text',
                'dependency' => array('advertisement', '!=', ''),
                'class'    =>'compact',
                
            ),
             array(
                'title'   => '右下角蒲公英',
                'label'   => '开启后网站底部将显示动态蒲公英特效',
                'id'      => 'plbj5',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '底部导航栏',
                'label'   => '开启后可自定义网站底部导航',
                'id'      => 'plbj4',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '文案&时间',
                'dependency' => array('plbj4', '!=', ''),
                'desc'    => '请填写左侧文案和时间',
                'id'      => 'bottomnav0',
                'default' => false,
                'type'    => 'text',
            ),
             array(
                'title'   => ' ',
                'desc'   => '请填写您的建站时间，如：2022-20-25',
                'id'      => 'timeauthor1',
                'default' => false,
                'type'    => 'text',
                'dependency' => array('plbj4', '!=', ''),
                'class'    =>'compact',
                
            ),
             array(
                'title'   => '导航一',
                'dependency' => array('plbj4', '!=', ''),
                'desc'    => '请填写导航文字',
                'id'      => 'bottomnav1',
                'default' => false,
                'type'    => 'text',
            ),
             array(
                'title'   => ' ',
                'dependency' => array('plbj4', '!=', ''),
                'desc'    => '请填写导航链接',
                'id'      => 'bottomhre1',
                'class'    =>'compact',
                'default' => false,
                'type'    => 'text',
            ),
             array(
                'title'   => '导航二',
                'dependency' => array('plbj4', '!=', ''),
                'id'      => 'bottomnav2',
                'desc'    => '请填写导航文字',
                'default' => false,
                'type'    => 'text',
            ),
             array(
                'title'   => ' ',
                'dependency' => array('plbj4', '!=', ''),
                'desc'    => '请填写导航链接',
                'class'    =>'compact',
                'id'      => 'bottomhre2',
                'default' => false,
                'type'    => 'text',
            ),
             array(
                'title'   => '导航三',
                'dependency' => array('plbj4', '!=', ''),
                'desc'    => '请填写导航文字',
                'id'      => 'bottomnav3',
                'default' => false,
                'type'    => 'text',
            ),
             array(
                'title'   => ' ',
                'dependency' => array('plbj4', '!=', ''),
                'desc'    => '请填写导航链接',
                'id'      => 'bottomhre3',
                'class'    =>'compact',
                'default' => false,
                'type'    => 'text',
            ),
             array(
                'title'   => '导航四',
                'dependency' => array('plbj4', '!=', ''),
                'desc'    => '请填写导航文字',
                'id'      => 'bottomnav4',
                'default' => false,
                'type'    => 'text',
            ),
             array(
                'title'   => ' ',
                'dependency' => array('plbj4', '!=', ''),
                'desc'    => '请填写导航链接',
                'class'    =>'compact',
                'id'      => 'bottomhre4',
                'default' => false,
                'type'    => 'text',
            ),
             array(
                'title'   => '导航五',
                'dependency' => array('plbj4', '!=', ''),
                'desc'    => '请填写导航文字',
                'id'      => 'bottomnav5',
                'default' => false,
                'type'    => 'text',
            ),
             array(
                'title'   => ' ',
                'dependency' => array('plbj4', '!=', ''),
                'desc'    => '请填写导航链接',
                'class'    =>'compact',
                'id'      => 'bottomhre5',
                'default' => false,
                'type'    => 'text',
            ),
      ),));
      
      CSF::createSection($prefix, array(
        'parent'      => 'jubu',
        'title'       => '左侧',
        'icon'        => 'fa fa-arrow-circle-left',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
             array(
                'title'   => '左边联系站长QQ',
                'label'   => '开启后，电脑左侧边栏显示"联系站长”按钮',
                'desc'    => '注意：站长需要在前端个人中心填写个人QQ，否则无法实现跳转QQ<br>'.$shouquan_text,
                'id'      => 'contact_help_qq',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '左边随便看看按钮',
                'label'   => '开启后，电脑左侧边栏显示"随便看看”按钮',
                'id'      => 'suibiankankan',
                'default' => false,
                'type'    => 'switcher',
            ),
      ),));
       CSF::createSection($prefix, array(
        'parent'      => 'jubu',
        'title'       => '顶部',
        'icon'        => 'fa fa-arrow-circle-up',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
              array(
                'title'   => '元旦灯笼+梅花特效',
                'label'   => '启用后，网站右上角将呈现梅花和元旦灯笼特效',
                'id'      => 'chunjie',
                'default' => false,
                'type'    => 'switcher',
            ),
              array(
                'title'   => '顶部彩色进度条',
                'label'   => '启用后，网站顶部将显示一个彩色的进度条',
                'id'      => 'dingbu_jindutiao',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '幻灯片指示器优化',
                'label'   => '启用后，幻灯片指示器将会圆角显示',
                'id'      => 'swiper',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '自定义顶部切换标签',
                'label'   => '（你别走吖 ʕ ᵔᴥᵔ ʔ）（欢迎回来o( ❛ᴗ❛ o)',
                'id'      => 'dingbubiaoti',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => ' ',
                'desc'   => '当用户处于当前页面时的title文案)',
                'id'      => 'dingbubiaoti_mj1',
                'class'    =>'compact',
                'dependency' => array('dingbubiaoti', '!=', ''),
                'default' => '欢迎回来o( ❛ᴗ❛ ',
                'type'    => 'text',
            ),
            array(
                'title'   => ' ',
                'class'    =>'compact',
                'desc'   => '当用户离开当前页面时的title文案)',
                'id'      => 'dingbubiaoti_mj2',
                'dependency' => array('dingbubiaoti', '!=', ''),
                'default' => '你别走吖 ʕ ᵔᴥᵔ ʔ',
                'type'    => 'text',
            ),
             array(
                'title'   => '自定义顶部轮播标签',
                'id'      => 'dongtaibiaoti',
                'default' => false,
                'type'    => 'switcher',
                'label'    => '启用后，网站标签的title会显示一段轮播文字，注意，不能和“切换标签”混用',
            ),
             array(
                'title'   => ' ',
                'id'      => 'dongtaibiaoti1',
                'class'    =>'compact',
                'dependency' => array('dongtaibiaoti', '!=', ''),
                'default' => false,
                'type'    => 'text',
                'desc'    => '填写内容后，网站标签将会显示该内容的字幕，不填则不显示',
            ),
      ),));
    CSF::createSection($prefix, array(
        'id'    => 'wenzhang',
        'title' => '文章美化',
        'icon'  => 'fa fa-pencil-square-o',
    ));
     CSF::createSection($prefix, array(
        'parent'      => 'wenzhang',
        'title'       => '文章页面',
        'icon'        => 'fa fa-newspaper-o',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
            array(
                'title'   => '文章随机彩色标签',
                'label'   => '开启后文章的标签将会变成随机彩色',
                'id'      => 'colorfultag',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '评论区背景图片',
                'desc'    => '<br><img src="'.$img.'comment_bg.gif "height="90px">',
                'label'   => '启用后，文章末尾评论区会有背景图片',
                'id'      => 'plbj',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '文章阴影边缘',
                'label'   => '启用后，文章页将会添加一个淡绿色柔光边缘',
                'id'      => 'article_box_shadow',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '文章内图片边框光效',
                'label'   => '开启后，当鼠标移向文章页面内的图片时，图片周围会有绿色柔光显示',
                'id'      => 'post_page_img_shadow',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '文章标题美化',
                'label'   => '文章H2、H3标题美化，不再有下划线',
                'desc'    => $shouquan_text,
                'id'      => 'biaoti',
                'default' => false,
                'type'    => 'switcher',
            ),
      ),));
    
         CSF::createSection($prefix, array(
        'parent'      => 'wenzhang',
        'title'       => '文章列表',
        'icon'        => 'fa fa-bars',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
                array(
                'title'   => '隐藏首页文章发布时间',
                'label'   => '开启后用户将不能在首页看到文章的发布时间,文章页面还是可以看到的',
                'id'      => 'zibll_post_public_date',
                'default' => false,
                'type'    => 'switcher',
            ),
                array(
                'title'   => '首页文章列表悬停上浮',
                'label'   => '开启后给网站首页文章赋予悬停上浮特效',
                'id'      => 'posts_item',
                'default' => false,
                'type'    => 'switcher',
            ),
              array(
                'title'   => '首页文章列表水波上浮',
                'label'   => '开启后给网站首页文章赋予悬停上浮特效',
                'desc'    => '注意，水波上浮与悬停上浮只能选择一个喔~',
                'id'      => 'posts_item2',
                'default' => false,
                'type'    => 'switcher',
            ),
                array(
                'title'   => '首页文章点击更多美化',
                'label'   => '启用后，美化文章的“点击更多”按钮',
                'id'      => 'dianjigengduo',
                'default' => false,
                'type'    => 'switcher',
            ),
      ),));
      
     CSF::createSection($prefix, array(
        'parent'      => 'wenzhang',
        'title'       => '用户头像',
        'icon'        => 'fa fa-user-circle',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
              array(
                'title'   => '用户头像美化',
                'label'   => '头像彩色呼吸光环+悬停放大',
                'id'      => 'avatargh',
                'default' => false,
                'type'    => 'switcher',
            ),
      ),));
    CSF::createSection($prefix, array(
        'id'    => 'gongneng',
        'title' => '功能设置',
        'icon'  => 'fa fa-pie-chart',
    ));
     CSF::createSection($prefix, array(
        'parent'      => 'gongneng',
        'title'       => '弹窗提示',
        'icon'        => 'fa fa-crop',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
            array(
                'title'   => '日间、夜间切换提示',
                'label'   => '启用后，进行日间夜间模式切换时，谁有弹窗提示',
                'id'      => 'qiehuan',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '复制成功提示框1',
                'label'   => '启用后，当用户复制内容时会有弹窗提示',
                'id'      => 'fuzhitishi1',
                'default' => false,
                'type'    => 'switcher',
            ),
              array(
                'title'   => '复制成功提示框2',
                'label'   => '启用后，当用户复制内容时会有弹窗提示',
                'id'      => 'fuzhitishi2',
                'default' => false,
                'type'    => 'switcher',
            ),
               array(
                'title'   => '复制成功提示框3',
                'label'   => '启用后，当用户复制内容时会有弹窗提示',
                'id'      => 'fuzhitishi3',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '复制成功提示框4',
                'label'   => '启用后，当用户复制内容时会有弹窗提示',
                'id'      => 'fuzhitishi4',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '复制后保存原文地址',
                'label'   => '启用后，用户复制内容后同时会将原文地址复制到粘贴板上',
                'id'      => 'noft1',
                'default' => false,
                'type'    => 'switcher',
            ),
            
      ),));
      CSF::createSection($prefix, array(
        'parent'      => 'gongneng',
        'title'       => '音乐模块',
        'icon'        => 'fa fa-music',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
            array(
                'title'   => '添加音乐播放器',
                'label'   => '开启后可以给网站添加一个音乐播放器',
                'id'      => 'video',
                'default' => false,
                'type'    => 'switcher',
            ),
             
      ),));
    
    CSF::createSection($prefix, array(
        'parent'      => 'gongneng',
        'title'       => '禁用设置',
        'icon'        => 'fa fa-ban',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
             array(
                'title'   => '禁用鼠标右键',
                'label'   => '启用后，用户将不能使用右键进行任何操作',
                'id'      => 'noyou',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '禁止图片拖放',
                'label'   => '启用后，用户将不能拖放网站中图片',
                'id'      => 'notuofang',
                'default' => false,
                'type'    => 'switcher',
            ),
             array(
                'title'   => '禁用F12键',
                'label'   => '启用后，用户将不能使用F12键查询您的网站源码',
                'id'      => 'noft',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => ' ',
                'desc'   => '请输入自定义F12提示语，如：小子！别想扒站！',
                'dependency' => array('noft', '!=', ''),
                'class'    =>'compact',
                'id'      => 'nofttext',
                'default' => '坏孩子',
                'type'    => 'text',
            ),
             array(
                'title'   => '禁止内容选中',
                'label'   => '启用后，用户将不能选中网站中任意内容',
                'desc'    => '注：对用户不友好，慎选！',
                'id'      => 'nofta',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '禁止Ctrl+S保存网页',
                'label'   => '启用后，用户将不能Ctrl+S保存网页内容',
                'id'      => 'noftb',
                'default' => false,
                'type'    => 'switcher',
            ),
            
      ),));

CSF::createSection( $prefix, array(
    'title'        => '静态&托管',
    'icon'         => 'fa fa-handshake-o',
    'fields'       => CSF_Module_Static::static(),
  ));
   CSF::createSection( $prefix, array(
	      'title'       => '导入&导出',
	      'icon'        => 'fa fa-fw fa-copy',
	      'description' => '',
	      'fields'      => array(
	        array(
	          'type' => 'backup',
	        ),
	   ),
  ));