<?php
$prefix = 'vxras_options';
$img = '/wp-content/themes/vxras/img/';
if ('topics' == $type) {
$query_args = array('taxonomy' => 'topics');
}
  CSF::createSection($prefix, array(
		'id'    => 'global',
		'title' => '更多功能',
		'icon'  => 'fa fa-fw fa-bullseye',
	));
CSF::createSection($prefix, array(
        'parent'      => 'global',
        'title'       => '文章功能',
        'icon'        => 'fa fa-file-text',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
        array(
            'id'    => 'posts_item_number',
            'type'  => 'switcher',
            'title' => '卡片模式数量修改',
            'desc' => '修改一列显示几个卡片<code>20%</code>是一排显示5个卡片<code>10%</code>则是十个',
        ),
        array(
                'dependency' => array('posts_item_number', '!=', ''),
                'title' => ' ', 
                'subtitle'    => '卡片参数',
                'id' => 'posts_item_number_s', 
                'default' => 20,
                'unit'     => '%',
                'max'      => 100,
                'min'      => 1,
                'step'     => 1,
                'unit'     => '%',
                'type'     => 'spinner',
                'class'    =>'compact',
            ), 
        array(
            'id'    => 'shanchu_fujian',
            'type'  => 'switcher',
            'title' => '删除文章自动删除图片附件',
        ),
        array(
            'id'    => 'posts_gqts',
            'type'  => 'switcher',
            'title' => '文章底部添加过期提示',
        ),
        array(
            'dependency' => array('posts_gqts', '!=', ''),
            'id'     => 'posts_gqts_sz',
            'type'   => 'fieldset',
            'title'  => '文章底部添加过期提示参数设置',
            'fields' => array(
                array(
                    'id'         => 'text',
                    'type'  => 'textarea',
                    'title'      => '过期提示内容',
                    'default' => '
某些文章具有时效性，若有错误或已失效，请在下方
<a href="#comment">留言</a>或联系
<a target="_blank" title="'. get_bloginfo('name') .'" href="'. get_bloginfo('url') .'">
<b>'. get_bloginfo('name') .'</b>
</a>。
                    ',
                ),
            ),
        ),
        
    ),
));
CSF::createSection($prefix, array(
        'parent'      => 'global',
        'title'       => '常用功能',
        'icon'        => 'fa fa-codepen',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
            array(
            'id'    => 'weihu',
            'type'  => 'switcher',
            'title' => '网站维护模式',
        ),
        array(
            'dependency' => array('weihu', '!=', ''),
            'id'     => 'weihu_sz',
            'type'   => 'fieldset',
            'title'  => '网站维护模式参数设置',
            'fields' => array(
                array(
                    'id'         => 'ztm',
                    'type'  => 'text',
                    'title'      => '网页响应状态码',
                    'default' => '503',
                ),
                array(
                    'id'            => 'core',
                    'type'          => 'wp_editor',
                    'title'         => '网站维护模式自定义显示内容',
                    'tinymce'       => true,
                    'quicktags'     => true,
                    'media_buttons' => true,
                    'height'        => '300px',
                ),
            ),
        ),
            array(
			'id'       => 'custom_payment_order_success',
			'type'     => 'switcher',
			'title'    => '开通会员自动认证',
		    ),
		    array(
		        'dependency' => array('custom_payment_order_success', '!=', ''),
		        'id'       => 'auth_name',
		        'type'     => 'text',
		        'title'    => ' ',
		        'desc'     => '认证名',
		        'default'     => ''.get_bloginfo('name').'官方认证',
		    ),
		    array(
		        'dependency' => array('custom_payment_order_success', '!=', ''),
		        'id'       => 'auth_desc',
		        'type'     => 'text',
		        'title'    => ' ',
		        'desc'     => '认证详情',
		        'default'     => ''.get_bloginfo('name').'官方认证用户',
		    ),
            array(
			'id'       => 'luesuotu',
			'type'     => 'switcher',
			'title'    => '禁止Wordpress自动生成略缩图',
			'label'    => '启用后，Wordpress将不会再生成略缩图',
		),
            array(
			'id'       => 'add_yx_box',
			'type'     => 'switcher',
			'title'    => '邮件通知',
			'default' => true,
			'desc'   => '启用后，文章发布/更新将会邮件通知用户',
		),
      ),));
CSF::createSection($prefix, array(
        'parent'      => 'global',
        'title'       => '特殊定制功能',
        'icon'        => 'fa fa-gitlab',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
            array(
		    	'id'       => 'Cheat_code',
		    	'type'     => 'switcher',
		    	'title'    => '作弊码',
		    	'desc'   => '开启后将不在显示购买框，PC端需要上上下下左右左右显示，手机端点击三次屏幕～',
	    	),
            array(
		    	'id'       => 'tiaotiaocss',
		    	'type'     => 'switcher',
		    	'title'    => '果冻效果',
		    	'desc'   => '快来感受一下自定义果冻弹跳效果吧～',
	    	),
		    array(
            'id' => 'tiaotiaocss_gengduo',
            'class'    =>'compact',
            'type' => 'group',
            'title' => '添加更多',
            'desc'   => '需要带上<code>.</code>以及<code>#</code>，点击查看<a href="https://www.vxras.com/2315.html" target="_blank">#配置教程</a>',
            'dependency' => array('tiaotiaocss', '==', 'true'),
            'fields' => array(
                array(
                    'id' => 'beizhu',
                    'type' => 'text',
                    'title' =>  '备注',
                    'desc'   => '无实际意义，只是让你们方便记',
                    'default' =>  '文章卡片',
                ),
                array(
                    'id' => 'csscode',
                    'class'    =>'compact',
                    'type' => 'text',
                    'title' =>  'CSS',
                    'desc'   => '菜就多练，让你感受一下自己给区块添加css的感觉',
                    'default' =>  'posts.posts-item.card.ajax-item',
                ),
            ),
        ),
            array(
		    	'id'       => 'show_only_login',
		    	'type'     => 'switcher',
		    	'title'    => '登录才能查看网站内容',
		    	'label'   => '启用后，未登录用户查看网站内容跳转登录页',
	    	),
	    	array(
	    		'id'       => 'n_yingcang_css',
	    		'type'     => 'switcher',
	    		'title'    => '未登录全站图片模糊',
	    		'label'   => '启用后，网站所有图片都模糊显示',
	    	),
	    	array(
	    		'id'       => 'n_yingcang_css2',
	    		'type'     => 'switcher',
	    		'title'    => '未登录文章详情页内图片模糊',
	    		'label'   => '启用后，文章页面所有图片都模糊显示',
	    	),
            array(
		    	'id'    => 'mobiles',
		    	'type'  => 'switcher',
		    	'title' => '网站只允许手机端访问',
		    	'desc'  => '明日香定制功能',
            ),
            array(
                'title'   => '自动清理僵尸粉',
                'label'   => '启用后，自动清理三个月未登录用户',
                'id'      => 'fbtz',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
            'id'         => 'vxras_Togreet',
            'type'       => 'switcher',
            'title'      => '是否显示网站时段问候语',
            // 'desc'      => '开启后信息页报错，暂未解决这个问题',
            'help'      => '开启感觉萌萌哒',
            'default'    => false,
        ),
                array(
                    'dependency' => array('vxras_Togreet', '==', 'true'),
                    'id'         => 'vxras_huanying_text',
                    'type'       => 'text',
                    'title'      => '欢迎语',
                    'dsec'       => '进入网站时的欢迎语',
                    'default'    => '欢迎访问本站<br>您的访问时本站的荣幸<br>希望您能在本站<br>找到您想要的资源',           
                ),
                array(
                    'dependency' => array('vxras_Togreet', '==', 'true'),
                    'id'         => 'vxras_wuye_text',
                    'type'       => 'text',
                    'title'      => '时段问候语午夜',
                    'dsec'       => '时段问候语午夜文本',
                    'default'    => '初一小盏提示您 午夜骚年，快睡觉去，妹纸等你太久了会不耐烦的哦！',           
                ),
                array(
                    'dependency' => array('vxras_Togreet', '==', 'true'),
                    'id'         => 'vxras_zaoshang_down',
                    'type'       => 'text',
                    'title'      => '时段问候语早上',
                    'dsec'       => '时段问候语早上文本',
                    'default'    => '早上好~今天又是元气满满的一天哦！先去尝尝鲜</a>~',           
                ),
                array(
                    'dependency' => array('vxras_Togreet', '==', 'true'),
                    'id'         => 'vxras_shangwu_down',
                    'type'       => 'text',
                    'title'      => '时段问候语上午',
                    'dsec'       => '时段问候语上午文本',
                    'default'    => '最难的任务适合在上午时段攻克哦，期待您的订单~',           
                ),
                array(
                    'dependency' => array('vxras_Togreet', '==', 'true'),
                    'id'         => 'vxras_zhongwu_down',
                    'type'       => 'text',
                    'title'      => '时段问候语中午',
                    'dsec'       => '时段问候语中午文本',
                    'default'    => '中午拿什么填补我空虚的胃和心灵？<br />停下手中的工作，快去吃饭吧，晚了就没的吃了',           
                ),
                array(
                    'dependency' => array('vxras_Togreet', '==', 'true'),
                    'id'         => 'vxras_xiawu_down',
                    'type'       => 'text',
                    'title'      => '时段问候语下午',
                    'dsec'       => '时段问候语下午文本',
                    'default'    => '下午时段初一小盏正在优化细节，力求做一个人见人爱的“细节控”哦~',           
                ),
                array(
                    'dependency' => array('vxras_Togreet', '==', 'true'),
                    'id'         => 'vxras_bangwan_texte',
                    'type'       => 'text',
                    'title'      => '时段问候语傍晚',
                    'dsec'       => '时段问候语傍晚文本',
                    'default'    => '快要下班了吧？休息会扒根烟喝杯茶~',           
                ),
                 array(
                    'dependency' => array('vxras_Togreet', '==', 'true'),
                    'id'         => 'vxras_yewan_link',
                    'type'       => 'text',
                    'title'      => '时段问候语夜晚',
                    'dsec'       => '时段问候语夜晚文本',
                    'default'    => '晚安~音乐、运动、阅读，睡前时间放松一下，灵感也许会悄悄到来！',        
                ), 
                array(
                    'dependency' => array('vxras_Togreet', '==', 'true'),
                    'id'         => 'vxras_xiuxi_down',
                    'type'       => 'text',
                    'title'      => '时段问候语该休息了',
                    'dsec'       => '时段问候语该休息了文本',
                    'default'    => '累了就早点休息~<br />晚间22：00-5:00是最佳睡眠时间哦',
            )
      ),));
CSF::createSection($prefix, array(
        'parent'      => 'global',
        'title'       => '会员进群',
        'icon'        => 'fa fa-gitlab',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
            array(
                'id' => 'zyx_user_vip_svgs',
                'title' => '自定义svg标识',
                'type' => 'textarea',
                'default' => '<svg t="1701350668481" class="em16 mr6" viewBox="0 0 1169 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="1688" width="200" height="200"><path d="M767.302664 954.980805l384.527669-451.667421a82.633541 82.633541 0 0 0 6.573122-91.554207l-131.462451-229.120272a82.633541 82.633541 0 0 0-71.36533-41.31677H449.445237a82.633541 82.633541 0 0 0-71.36533 41.31677l-131.462451 229.120272a82.633541 82.633541 0 0 0 6.103614 91.554207l384.997178 451.667421a82.164032 82.164032 0 0 0 129.584416 0z" fill="#51F2F2" p-id="1689"></path><path d="M561.65783 1023.998591a136.157539 136.157539 0 0 1-108.456523-53.054489l-422.557878-495.331735a136.157539 136.157539 0 0 1-12.207227-154.46838l144.608696-252.1262A138.035574 138.035574 0 0 1 282.300121 0h557.776399a138.035574 138.035574 0 0 1 119.255224 69.017787l75.1214 130.992942a46.950875 46.950875 0 1 1-81.225014 46.950875l-75.121401-130.523433a44.133823 44.133823 0 0 0-38.030209-22.066912H283.239139a44.133823 44.133823 0 0 0-38.030209 22.066912L100.130725 368.094863a43.194805 43.194805 0 0 0 3.286561 46.950875l422.557878 495.331735a46.950875 46.950875 0 0 0 69.956805 0l422.557878-498.148787a42.725297 42.725297 0 0 0 2.347544-46.950876 46.950875 46.950875 0 1 1 81.225014-46.950875 136.157539 136.157539 0 0 1-10.798701 153.059854l-422.557879 498.618296a135.218521 135.218521 0 0 1-107.047995 53.993506z" fill="#333333" p-id="1690"></path><path d="M561.65783 743.701866a90.145681 90.145681 0 0 1-71.83484-35.213157L282.76963 441.807737A46.950875 46.950875 0 0 1 291.220787 375.607003a46.950875 46.950875 0 0 1 65.731226 8.451157l207.05336 266.680972 202.358273-266.680972A46.950875 46.950875 0 0 1 832.094872 375.607003a46.950875 46.950875 0 0 1 8.451157 66.200734l-207.05336 266.680972a90.145681 90.145681 0 0 1-71.834839 35.213157z" fill="#333333" p-id="1691"></path></svg>',
                'attributes' => array(
                    'rows' => 4,
                ) ,
                'sanitize' => false,
            ) ,
            array(
                'title' => '是否允许封禁用户入群',
                'id' => 'zyx_user_ban',
                'type' => 'switcher',
                'default' => false,
            ) ,
            array(
                'title' => '入群介绍',
                'desc' => '用户申请入群的时候显示的介绍内容',
                'id' => 'desc',
                'default' => '<div class="ml10">
  <li>进群后不得打广告，违规者直接踢除</li>
  <li>不得向他人发送此群的QQ号，违规者直接踢除</li>
  <li class="c-red">请注意!!一旦退群将无法再次加群!!</li>
  <li class="c-red">QQ号请输入正确否则无法进群</li>
</div>',
                'sanitize' => false,
                'type' => 'textarea',
                'attributes' => array(
                    'rows' => 3,
                ) ,
            ) ,
            array(
                'id' => 'ewm',
                'type' => 'upload',
                'title' => '群二维码',
                'preview' => true,
            ),
            array(
                'id' => 'qunhao',
                'title' => '群号',
                'class' => 'mini-input',
                'default' => '1234567',
                'type' => 'text',
            ),
            array(
                'id' => 'qunurl',
                'type' => 'text',
                'title' => __('群URL地址', 'zib_language'),
            ),
        ),
    ));
CSF::createSection($prefix, array(
        'parent'      => 'global',//没写完，如果你要用就请删除-1
        'title'       => '权限分配',
        'icon'        => 'fa fa-gitlab',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
            array(
            'type'    => 'submessage',
            'style'   => 'warning',
            'content' => '<h3 style="color:#fd4c73;">更强大的权限分配系统</h3>
           <p>如果你希望给每个层级的用户分配不同的权限，那么这里可以满足你的需求</p>
           <p>请至少每个选项都提供一个选择给用户，留空则无限制</p>
           <p>特殊页面为必填项！！！</p>',
           'style' => 'warning',
           'type' => 'submessage',
        ),
        array(
            'id'    => 'vxras_show_only_login',
            'type'  => 'switcher',
            'title' => '开启贤者模式',
        ),
        array(
                'dependency' => array('vxras_show_only_login', '==', 'true'),
                'class'    =>'compact',
                'id'      => 'vxras_show_only_login_moshi',
                'default' => 'whitelist',
                'type'    => 'radio',
                'title'   => '模式选择',
                'inline'  => true,
                'desc'    => '白名单模式：声明允许访问的页面<br>黑名单模式：声明禁止访问的页面<br>建议使用黑名单模式',
                'options' => array(
                    'null'   => '不开启',
                    'whitelist'  => '白名单模式',
                    'blacklist' => '黑名单模式',
                ),
            ),
        array(
            'dependency' => array('vxras_show_only_login', '==', 'true'),
            'style'    => 'border-color: #eee0;',
            'id'    => 'vxras_show_only_login_notlogin',
            'type'  => 'submessage',
            'title' => '未登录用户权限设置',
        ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=', '', '', 'visible'),
                'id'          => 'vxras_show_only_login_notlogin_cats',
                'title'       => ' ',
                'subtitle'    => '分类名单',
                'default'     => array(),
                'options'     => 'categories',
                'placeholder' => '输入关键词以搜索分类',
                'ajax'        => true,
                'chosen'      => true,
                'multiple'    => true,
                'sortable'    => true,
                'settings'    => array(
                    'min_length' => 2,
                ),
                'type'        => 'select',
            ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=|!=', ''),
                'title'       => ' ',
                'subtitle'    => '专题名单',
                'id'          => 'vxras_show_only_notlogin_topics',
                'class'       => 'compact',
                'placeholder' => '输入关键词以搜索专题',
                'default'     => array(),
                'options'     => 'tag',
                'query_args'  => array('taxonomy' => 'topics', 'hide_empty' => false),
                'type'        => 'select',
                'ajax'        => true,
                'chosen'      => true,
                'multiple'    => true,
                'sortable'    => true,
                'settings'    => array(
                    'min_length' => 2,
                ),
            ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=|!=', ''),
                'id'          => 'vxras_show_only_login_notlogin_tag',
                'title'       => ' ',
                'subtitle'    => '标签名单',
                'class'       => 'compact',
                'options'     => 'tag',
                'query_args'  => $query_args,
                'type'        => 'select',
                'placeholder' => '输入关键词以搜索标签',
                'chosen'      => true,
                'multiple'    => true,
                'sortable'    => true,
                'ajax'        => true,
                'settings'    => array(
                    'min_length' => 2,
                ),
            ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=', '', '', 'visible'),
                'id'          => 'vxras_show_only_login_notlogin_single',
                'class'       => 'compact',
                'title'       => ' ',
                'subtitle'    => '文章名单',
                'default'     => '',
                'options'     => 'posts',
                'placeholder' => '输入文章标题关键词以搜索文章',
                'chosen'      => true,
                'ajax'        => true,
                'multiple'    => true,
                'settings'    => array(
                    'min_length' => 2,
                ),
                'type'        => 'select',
            ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=', '', '', 'visible'),
                'id'          => 'vxras_show_only_login_notlogin_page',
                'class'       => 'compact',
                'title'       => ' ',
                'subtitle'    => '页面名单',
                'default'     => '',
                'options'     => 'page',
                'placeholder' => '输入关键词以搜索页面',
                'chosen'      => true,
                'ajax'        => true,
                'multiple'    => true,
                'settings'    => array(
                    'min_length' => 2,
                ),
                'type'        => 'select',
            ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=', '', '', 'visible'),
                'id' => 'vxras_show_only_login_notlogin_special',
                'title' => ' ',
                'class'       => 'compact',
                'subtitle'=> '特殊页面',
                'desc'=> '&nbsp&nbsp1:首页&nbsp&nbsp2:登录页&nbsp&nbsp3:搜索页&nbsp&nbsp4:404错误页&nbsp&nbsp5:后台页面&nbsp&nbsp100:所有页面',
                'placeholder' => '使用英文逗号分隔',
                'default' => '',
                'type' => 'text',
            ),
        array(
            'dependency' => array('vxras_show_only_login', '==', 'true'),
            'style'    => 'border-color: #eee0;',
            'id'    => 'vxras_show_only_login_averageuser',
            'type'  => 'submessage',
            'title' => '已登录用户权限设置',
        ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=', '', '', 'visible'),
                'id'          => 'vxras_show_only_login_averageuser_cats',
                'title'       => ' ',
                'subtitle'    => '分类名单',
                'default'     => array(),
                'options'     => 'categories',
                'placeholder' => '输入关键词以搜索分类',
                'ajax'        => true,
                'chosen'      => true,
                'multiple'    => true,
                'sortable'    => true,
                'settings'    => array(
                    'min_length' => 2,
                ),
                'type'        => 'select',
            ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=|!=', ''),
                'title'       => ' ',
                'subtitle'    => '专题名单',
                'id'          => 'vxras_show_only_averageuser_topics',
                'class'       => 'compact',
                'placeholder' => '输入关键词以搜索专题',
                'default'     => array(),
                'options'     => 'tag',
                'query_args'  => array('taxonomy' => 'topics', 'hide_empty' => false),
                'type'        => 'select',
                'ajax'        => true,
                'chosen'      => true,
                'multiple'    => true,
                'sortable'    => true,
                'settings'    => array(
                    'min_length' => 2,
                ),
            ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=|!=', ''),
                'id'          => 'vxras_show_only_login_averageuser_tag',
                'title'       => ' ',
                'subtitle'    => '标签名单',
                'class'       => 'compact',
                'options'     => 'tag',
                'query_args'  => $query_args,
                'type'        => 'select',
                'placeholder' => '输入关键词以搜索标签',
                'chosen'      => true,
                'multiple'    => true,
                'sortable'    => true,
                'ajax'        => true,
                'settings'    => array(
                    'min_length' => 2,
                ),
            ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=', '', '', 'visible'),
                'id'          => 'vxras_show_only_login_averageuser_single',
                'class'       => 'compact',
                'title'       => ' ',
                'subtitle'    => '文章名单',
                'default'     => '',
                'options'     => 'posts',
                'placeholder' => '输入文章标题关键词以搜索文章',
                'chosen'      => true,
                'ajax'        => true,
                'multiple'    => true,
                'settings'    => array(
                    'min_length' => 2,
                ),
                'type'        => 'select',
            ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=', '', '', 'visible'),
                'id'          => 'vxras_show_only_login_averageuser_page',
                'class'       => 'compact',
                'title'       => ' ',
                'subtitle'    => '页面名单',
                'default'     => '',
                'options'     => 'page',
                'placeholder' => '输入关键词以搜索页面',
                'chosen'      => true,
                'ajax'        => true,
                'multiple'    => true,
                'settings'    => array(
                    'min_length' => 2,
                ),
                'type'        => 'select',
            ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=', '', '', 'visible'),
                'id' => 'vxras_show_only_login_averageuser_special',
                'title' => ' ',
                'class'       => 'compact',
                'subtitle'=> '特殊页面',
                'desc'=> '&nbsp&nbsp1:首页&nbsp&nbsp2:登录页&nbsp&nbsp3:搜索页&nbsp&nbsp4:404错误页&nbsp&nbsp5:后台页面&nbsp&nbsp100:所有页面',
                'placeholder' => '使用英文逗号分隔',
                'default' => '',
                'type' => 'text',
            ),
        array(
            'dependency' => array('vxras_show_only_login', '==', 'true'),
            'style'    => 'border-color: #eee0;',
            'id'    => 'vxras_show_only_login_vip1',
            'type'  => 'submessage',
            'title' => 'VIP1用户权限设置',
        ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=', '', '', 'visible'),
                'id'          => 'vxras_show_only_login_vip1_cats',
                'title'       => ' ',
                'subtitle'    => '分类名单',
                'default'     => array(),
                'options'     => 'categories',
                'placeholder' => '输入关键词以搜索分类',
                'ajax'        => true,
                'chosen'      => true,
                'multiple'    => true,
                'sortable'    => true,
                'settings'    => array(
                    'min_length' => 2,
                ),
                'type'        => 'select',
            ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=|!=', ''),
                'title'       => ' ',
                'subtitle'    => '专题名单',
                'id'          => 'vxras_show_only_vip1_topics',
                'class'       => 'compact',
                'placeholder' => '输入关键词以搜索专题',
                'default'     => array(),
                'options'     => 'tag',
                'query_args'  => array('taxonomy' => 'topics', 'hide_empty' => false),
                'type'        => 'select',
                'ajax'        => true,
                'chosen'      => true,
                'multiple'    => true,
                'sortable'    => true,
                'settings'    => array(
                    'min_length' => 2,
                ),
            ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=|!=', ''),
                'id'          => 'vxras_show_only_login_vip1_tag',
                'title'       => ' ',
                'subtitle'    => '标签名单',
                'class'       => 'compact',
                'options'     => 'tag',
                'query_args'  => $query_args,
                'type'        => 'select',
                'placeholder' => '输入关键词以搜索标签',
                'chosen'      => true,
                'multiple'    => true,
                'sortable'    => true,
                'ajax'        => true,
                'settings'    => array(
                    'min_length' => 2,
                ),
            ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=', '', '', 'visible'),
                'id'          => 'vxras_show_only_login_vip1_single',
                'class'       => 'compact',
                'title'       => ' ',
                'subtitle'    => '文章名单',
                'default'     => '',
                'options'     => 'posts',
                'placeholder' => '输入文章标题关键词以搜索文章',
                'chosen'      => true,
                'ajax'        => true,
                'multiple'    => true,
                'settings'    => array(
                    'min_length' => 2,
                ),
                'type'        => 'select',
            ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=', '', '', 'visible'),
                'id'          => 'vxras_show_only_login_vip1_page',
                'class'       => 'compact',
                'title'       => ' ',
                'subtitle'    => '页面名单',
                'default'     => '',
                'options'     => 'page',
                'placeholder' => '输入关键词以搜索页面',
                'chosen'      => true,
                'ajax'        => true,
                'multiple'    => true,
                'settings'    => array(
                    'min_length' => 2,
                ),
                'type'        => 'select',
            ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=', '', '', 'visible'),
                'id' => 'vxras_show_only_login_vip1_special',
                'title' => ' ',
                'class'       => 'compact',
                'subtitle'=> '特殊页面',
                'desc'=> '&nbsp&nbsp1:首页&nbsp&nbsp2:登录页&nbsp&nbsp3:搜索页&nbsp&nbsp4:404错误页&nbsp&nbsp5:后台页面&nbsp&nbsp100:所有页面',
                'placeholder' => '使用英文逗号分隔',
                'default' => '',
                'type' => 'text',
            ),
        array(
            'dependency' => array('vxras_show_only_login', '==', 'true'),
            'style'    => 'border-color: #eee0;',
            'id'    => 'vxras_show_only_login_vip2',
            'type'  => 'submessage',
            'title' => 'VIP2用户权限设置',
        ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=', '', '', 'visible'),
                'id'          => 'vxras_show_only_login_vip2_cats',
                'title'       => ' ',
                'subtitle'    => '分类名单',
                'default'     => array(),
                'options'     => 'categories',
                'placeholder' => '输入关键词以搜索分类',
                'ajax'        => true,
                'chosen'      => true,
                'multiple'    => true,
                'sortable'    => true,
                'settings'    => array(
                    'min_length' => 2,
                ),
                'type'        => 'select',
            ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=|!=', ''),
                'title'       => ' ',
                'subtitle'    => '专题名单',
                'id'          => 'vxras_show_only_vip2_topics',
                'class'       => 'compact',
                'placeholder' => '输入关键词以搜索专题',
                'default'     => array(),
                'options'     => 'tag',
                'query_args'  => array('taxonomy' => 'topics', 'hide_empty' => false),
                'type'        => 'select',
                'ajax'        => true,
                'chosen'      => true,
                'multiple'    => true,
                'sortable'    => true,
                'settings'    => array(
                    'min_length' => 2,
                ),
            ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=|!=', ''),
                'id'          => 'vxras_show_only_login_vip2_tag',
                'title'       => ' ',
                'subtitle'    => '标签名单',
                'class'       => 'compact',
                'options'     => 'tag',
                'query_args'  => $query_args,
                'type'        => 'select',
                'placeholder' => '输入关键词以搜索标签',
                'chosen'      => true,
                'multiple'    => true,
                'sortable'    => true,
                'ajax'        => true,
                'settings'    => array(
                    'min_length' => 2,
                ),
            ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=', '', '', 'visible'),
                'id'          => 'vxras_show_only_login_vip2_single',
                'class'       => 'compact',
                'title'       => ' ',
                'subtitle'    => '文章名单',
                'default'     => '',
                'options'     => 'posts',
                'placeholder' => '输入文章标题关键词以搜索文章',
                'chosen'      => true,
                'ajax'        => true,
                'multiple'    => true,
                'settings'    => array(
                    'min_length' => 2,
                ),
                'type'        => 'select',
            ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=', '', '', 'visible'),
                'id'          => 'vxras_show_only_login_vip2_page',
                'class'       => 'compact',
                'title'       => ' ',
                'subtitle'    => '页面名单',
                'default'     => '',
                'options'     => 'page',
                'placeholder' => '输入关键词以搜索页面',
                'chosen'      => true,
                'ajax'        => true,
                'multiple'    => true,
                'settings'    => array(
                    'min_length' => 2,
                ),
                'type'        => 'select',
            ),
        array(
                'dependency'  => array('vxras_show_only_login', '!=', '', '', 'visible'),
                'id' => 'vxras_show_only_login_vip2_special',
                'title' => ' ',
                'class'       => 'compact',
                'subtitle'=> '特殊页面',
                'desc'=> '&nbsp&nbsp1:首页&nbsp&nbsp2:登录页&nbsp&nbsp3:搜索页&nbsp&nbsp4:404错误页&nbsp&nbsp5:后台页面&nbsp&nbsp100:所有页面',
                'placeholder' => '使用英文逗号分隔',
                'default' => '',
                'type' => 'text',
            ),
        ),
    ));