<?php
CSF::createSection($prefix, array(
        'id'    => 'vxras_all',
        'title' => '动漫风美化',
        'icon'  => 'fa fa-github-alt',
    ));
     CSF::createSection($prefix, array(
        'parent'      => 'vxras_all',
        'title'       => '全局美化',
        'icon'        => 'fa fa-codepen',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
            array(
                'title'   => 'H标题美化',
                'label'   => '将标题美化成可爱猫爪',
                'desc'    => '<br><img src="'.$img.'cat.svg" class="cat_h">',
                'id'      => 'cat_h',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '首页大图搜索框美化',
                'label'   => '修改大图搜索框部分样式',
                'desc'    => '',
                'id'      => 'header_slider_search',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '猫耳朵',
                'label'   => '给侧边栏以及下拉框等区块添加一个猫耳朵',
                'help'    => '侧边栏第一个区块、当前页面二维码、表情框等',
                'id'      => 'cat_all',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '简易化loading加载',
                'label'   => '支持日夜间自适应，建议换成自己的网站logo哦～',
                'id'      => 'logo_loading',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => ' ',
                'dependency' => array('logo_loading', '!=', ''),
                'desc'   => '日间logo',
                'id'      => 'body',
                'default' => false,
                'type'    => 'text',
            ),
            array(
                'title'   => ' ',
                'dependency' => array('logo_loading', '!=', ''),
                'desc'   => '夜间logo',
                'id'      => 'darktheme',
                'default' => false,
                'type'    => 'text',
            ),
            array(
                'title'   => '右侧调皮Loli',
                'label'   => '侧边栏增加一个调皮的小萝莉～',
                'id'      => 'tiaopill',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '边框拟态',
                'label'   => '自定义区块边框颜色，类似拟态风格～',
                'id'      => 'pinkh',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => ' ',
                'dependency' => array('pinkh', '!=', ''),
                'desc'   => '自定义颜色',
                'id'      => 'pinkh_color',
                'default' => '#FFD1D8',
                'type'    => 'color',
            ),
            array(
                'title'   => '会员开通颜色自定义',
                'label'   => '修改右上角会员开通颜色～',
                'id'      => 'hyktxc',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '会员开通弹窗',
                'label'   => '给会员开通弹窗增加两个小图～',
                'id'      => 'bilibili',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => ' ',
                'dependency' => array('bilibili', '!=', ''),
                'desc'   => '自定义左边小图',
                'id'      => 'bilibili_img1',
                'default' => 'https://s1.hdslb.com/bfs/seed/jinkela/short/mini-login-v2/img/22_open.4ea5f239.png',
                'type'    => 'upload',
            ),
            array(
                'title'   => ' ',
                'dependency' => array('bilibili', '!=', ''),
                'desc'   => '自定义右边小图',
                'id'      => 'bilibili_img2',
                'default' => 'https://s1.hdslb.com/bfs/seed/jinkela/short/mini-login-v2/img/33_open.f7d7f655.png',
                'type'    => 'upload',
            ),
            array(
                'title'   => ' ',
                'dependency' => array('bilibili', '!=', ''),
                'desc'   => '图片比例，最大30%',
                'id'      => 'bilibili_spinner',
                'default' => 20,
                'unit'     => '%',
                'max'      => 30,
                'min'      => 5,
                'step'     => 5,
                'unit'     => '%',
                'type'     => 'spinner',
            ),
            array(
                'title'   => '分类栏目',
                'label'   => '仅支持3-5个字，多了不支持～',
                'id'      => 'fenleilm',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '马里奥鼠标指针',
                'label'   => '将鼠标指针美化成马里奥手指～',
                'id'      => 'mario',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '侧边按钮',
                'label'   => '萌大白～',
                'id'      => 'vxrasxfan',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
			    'dependency' => array('post_ll', '!=', ''),
			    'title'   => '滑动时间',
			    'id'      => 'post_ll_s',
			    'default' => 0.5,
			    'min'     => 0,
			    'max'     => 10,
			    'step'    => 0.1,
			    'unit'    => '秒',
			    'type'    => 'spinner',
		    ),

      ),));
      CSF::createSection($prefix, array(
        'parent'      => 'vxras_all',
        'title'       => '文章列表',
        'icon'        => 'fa fa-twitch',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
            array(
                'title'   => '文章列表图片',
                'label'   => '列表、卡片图片倾斜放大',
                'id'      => 'post_xzfd',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '文章内图片圆角',
                'label'   => '文章内图片圆角显示',
                'id'      => 'post_radius',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => ' ',
                'desc'   => '',
                'id'      => 'post_radius_s',
                'default' => 20,
                'unit'     => 'PX',
                'max'      => 30,
                'min'      => 5,
                'step'     => 5,
                'type'     => 'spinner',
                'dependency' => array('post_radius', '!=', ''),
                'class'    =>'compact',
            ),
            array(
                'title'   => '评论区UID',
                'label'   => '评论区显示用户的ID',
                'id'      => 'comment_uid',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'dependency' => array('comment_uid', '==', 'true'),
                'class'    =>'compact',
                'id'      => 'comment_uid_type',
                'default' => 'id',
                'type'    => 'radio',
                'title'   => '显示信息',
                'inline'  => true,
                'options' => array(
                    'id'   => '用户ID',
                    'ip'  => '用户IP',
                    'city' => '用户所在城市',
                ),
            ),
            array(
                'title'   => ' ',
                'desc'   => '预留位，例如你网站有100用户预留5位则第一百位用户ID显示为<code style="color:red;">00100</code>',
                'id'      => 'comment_uid_s',
                'default' => 5,
                'unit'     => '位',
                'max'      => 30,
                'min'      => 3,
                'step'     => 1,
                'type'     => 'spinner',
                'dependency' => array('comment_uid', '!=', ''),
                'class'    =>'compact',
            ),
            array(
                'title'   => '评论区',
                'label'   => '评论区红、蓝背景轮询切换',
                'id'      => 'acgpl',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
			    'title'   => '文章列表悬停萝莉',
			    'label'    => '开启后文章列表悬停萝莉',
			    'id'      => 'post_ll',
			    'type'    => 'switcher',
			    'default' => false,
		),
		    array(
                'title'   => ' ',
                'desc'    =>'悬停图片',
                'dependency' => array('post_ll', '!=', ''),
                'id'      => 'post_ll_img',
                'class'    =>'compact',
                'default' => $img . 'decorate1.png',
                'type'    => 'switcher',
                'preview' => true,
                'library' => 'image', 
                'type' => 'upload',
            ),
            array(
                'title'   => '翻页按钮',
                'label'   => '如果你是使用按钮翻页，可以在此设置按钮为渐变色～',
                'id'      => 'fanyeanniu',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '加载更多',
                'label'   => '加载更多美化成粉色～',
                'id'      => 'jiazaigd',
                'default' => false,
                'type'    => 'switcher',
            ),
            
      ),));
      CSF::createSection($prefix, array(
        'parent'      => 'vxras_all',
        'title'       => '用户相关',
        'icon'        => 'fa fa-slideshare',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
            array(
                'title'   => '登录弹窗',
                'label'   => '给登录弹窗logo上方添加一个小萝莉～',
                'id'      => 'loginll',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '彩色昵称',
                'label'   => '用户昵称彩色～',
                'id'      => 'csnc',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '昵称抖动',
                'label'   => '给用户昵称增加一个炫彩抖动效果～',
                'id'      => 'dydd',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '头像摇摆',
                'label'   => '页面首次加载完小工具头像摇摆～',
                'id'      => 'avatar_yb',
                'default' => false,
                'type'    => 'switcher',
            ),
            array(
                'title'   => '侧边栏评论小工具',
                'label'   => '给侧边栏评论小工具加个背景～',
                'id'      => 'cblplxgj',
                'default' => false,
                'type'    => 'switcher',
            ),
      ),));
      CSF::createSection($prefix, array(
        'parent'      => 'vxras_all',
        'title'       => '区块美化',
        'icon'        => 'fa fa-github-alt',
        'description' => '',
        'default'   =>true,
        'fields'      => array(
            array(
                'title' => '首页用户', 
                'desc'    => '首页显示一个新注册用户以及会员用户展示区块',
                'id' => 'newuser', 
                'default' => false, 
                'type' => 'switcher'
            ), 
            array(
                'dependency' => array('newuser', '!=', ''),
                'title' => ' ', 
                'desc'    => '显示几位用户？',
                'id' => 'newuser_number', 
                'default' => 20,
                'unit'     => '%',
                'max'      => 100,
                'min'      => 10,
                'step'     => 1,
                'unit'     => '位',
                'type'     => 'spinner',
                'class'    =>'compact',
            ), 
            array(
                'dependency' => array('newuser', '!=', ''),
                'title' => ' ', 
                'desc'    => '右上角文字',
                'id' => 'newuser_desc', 
                'default' => '次元新星', 
                'type' => 'text',
                'class'    =>'compact',
            ),
            array(
                'dependency' => array('newuser', '!=', ''),
                'title' => ' ', 
                'desc'    => '第一排文字',
                'id' => 'newuser_new', 
                'default' => '最新注册', 
                'type' => 'text',
                'class'    =>'compact',
            ),
            array(
                'dependency' => array('newuser', '!=', ''),
                'title' => ' ', 
                'desc'    => '第二排文字',
                'id' => 'newuser_vip', 
                'default' => '会员用户', 
                'type' => 'text',
                'class'    =>'compact',
            ),
            array(
                'dependency' => array('newuser', '!=', ''),
                'title' => ' ', 
                'desc'    => '手机端不显示？',
                'id' => 'newuser_none', 
                'default' => true, 
                'type' => 'switcher',
                'class'    =>'compact',
            ),
            array(
                'title' => '六格统计区块', 
                'desc'    => '首页显示一个六格统计区块',
                'id' => 'liugetongji', 
                'default' => false, 
                'type' => 'switcher'
            ),
            array(
                'dependency' => array('liugetongji', '!=', ''),
                'title' => ' ', 
                'desc'    => '建站时间 例:<code>2023-08-29,9:30:01</code>可以只写年月日，也支持到秒',
                'id' => 'tongji_time', 
                'default' => '2023-08-29,9:30:01', 
                'type' => 'text',
                'class'    =>'compact',
            ),
            array(
                'title' => '底部排行榜', 
                'desc'    => '首页底部显示一个底部排行榜',
                'id' => 'ranking', 
                'default' => false, 
                'type' => 'switcher'
            ),
            array(
                'dependency' => array('ranking', '!=', ''),
                'title' => ' ', 
                'desc'    => '排行榜热度显示文字',
                'id' => 'ranking_hot_text', 
                'default' => '灵动值', 
                'type' => 'text',
                'class'    =>'compact',
            ),
            array(
                'dependency' => array('ranking', '!=', ''),
                'title' => ' ', 
                'desc'    => '排行榜页面地址，请在此填写排行榜页面的地址，用于排行榜底部显示跳转排行榜的按钮',
                'id' => 'ranking_url', 
                'default' => '/ranklist', 
                'type' => 'text',
                'class'    =>'compact',
            ),
        array(
            'id'          => 'danmu',
            'title'       => '右下角弹幕',
            'desc'        => '在页面右下角显示网站付费弹幕，移动端不显示',
            'type'        => "switcher",
            'default'     => false,
        ),
        array(
            'class'       => 'compact',
            'dependency'  => array( 'danmu', '==', true),
            'id'          => 'danmu_limit',
            'title'       => '弹幕显示条数',
            'desc'        => '显示的弹幕条数，请根据服务器配置调整',
            'default'     => 20,
            'max'         => 100,
            'min'         => 1,
            'step'        => 10,
            'unit'        => '条',
            'type'        => 'spinner',
        ),
        array(
            'class'    =>'compact',
            'dependency'  => array( 'danmu', '==', true),
            'id'          => 'danmu_auth',
            'title'       => '认证图标',
            'desc'        => '开启后显示认证图标',
            'type'        => "switcher",
            'default'     => false,
        ),
        array(
            'class'    =>'compact',
            'dependency'  => array( 'danmu', '==', true),
            'id'          => 'danmu_vip',
            'title'       => '会员图标',
            'desc'        => '开启后显示会员图标',
            'type'        => "switcher",
            'default'     => false,
        ),
        array(
            'class'    =>'compact',
            'dependency'  => array( 'danmu', '==', true),
            'id'          => 'danmu_medal',
            'title'       => '勋章图标',
            'desc'        => '开启后显示勋章图标',
            'type'        => "switcher",
            'default'     => false,
        ),
        array(
            'class'    =>'compact',
            'dependency'  => array( 'danmu', '==', true),
            'id'          => 'danmu_level',
            'title'       => '等级图标',
            'desc'        => '开启后显示等级图标',
            'type'        => "switcher",
            'default'     => false,
        ),
            array(
                'title' => '活动引导弹窗', 
                'desc'    => '首页显示一个新注册用户以及会员用户展示区块',
                'id' => 'play_vip', 
                'default' => false, 
                'type' => 'switcher'
            ),
            array(
                'title'   => ' ',
                'desc'   => '活动标题',
                'id'      => 'vip_title',
                'default' => '初一小盏限时钜惠',
                'type'    => 'text',
                'dependency' => array('play_vip', '!=', ''),
                'class'    =>'compact',
            ), 
            array(
                'title'   => ' ',
                'desc'   => '活动详情',
                'id'      => 'vip_subtitle',
                'default' => '2023年10月8日至12月28日',
                'type'    => 'text',
                'dependency' => array('play_vip', '!=', ''),
                'class'    =>'compact',
            ),
            array(
                'title'   => ' ',
                'desc'   => '按钮文字',
                'id'      => 'vip_btn',
                'default' => '永久会员仅需68￥',
                'type'    => 'text',
                'dependency' => array('play_vip', '!=', ''),
                'class'    =>'compact',
            ),
            array(
                'title'   => ' ',
                'desc'   => '图片',
                'id'      => 'vip_img',
                'default' => 'https://www.vxras.com/wp-content/uploads/2023/09/041.png',
                'type'    => 'upload',
                'dependency' => array('play_vip', '!=', ''),
                'class'    =>'compact',
            ),
            array(
                'title'   => ' ',
                'desc'   => '活动结束时间',
                'id'      => 'vip_time',
                'default' => '2023-12-28',
                'type'    => 'text',
                'dependency' => array('play_vip', '!=', ''),
                'class'    =>'compact',
            ),
            array(
                'dependency' => array('play_vip', '!=', ''),
                'title' => ' ', 
                'desc'    => '弹窗关闭后多久不再弹出？',
                'id' => 'vip_closetime', 
                'default' => 1,
                'unit'     => '%',
                'max'      => 100,
                'min'      => 0,
                'step'     => 1,
                'unit'     => '天',
                'type'     => 'spinner',
                'class'    =>'compact',
            ),
        array(
            'title' => '页脚美化', 
            'desc'    => '可爱的底部区块',
            'id' => 'moefooter', 
            'default' => false, 
            'type' => 'switcher'
        ), 
        array(
            'title'   => ' ',
            'desc'   => '导航一',
            'id'      => 'title1',
            'default' => '初一小盏',
            'type'    => 'text',
            'dependency' => array('moefooter', '!=', ''),
            'class'    =>'compact',
        ), 
        array(
            'title'   => ' ',
            'desc'   => '请填写导航一链接',
            'id'      => 'url1',
            'default' => 'https://www.vxras.com/',
            'type'    => 'text',
            'dependency' => array('moefooter', '!=', ''),
            'class'    =>'compact',
        ),
        array(
            'title'   => ' ',
            'desc'   => '导航二',
            'id'      => 'title2',
            'default' => '森鹿语',
            'type'    => 'text',
            'dependency' => array('moefooter', '!=', ''),
            'class'    =>'compact',
        ), 
        array(
            'title'   => ' ',
            'desc'   => '请填写导航二链接',
            'id'      => 'url2',
            'default' => 'https://www.lsenyu.cn/',
            'type'    => 'text',
            'dependency' => array('moefooter', '!=', ''),
            'class'    =>'compact',
        ),
        array(
            'title'   => ' ',
            'desc'   => '导航三',
            'id'      => 'title3',
            'default' => '冰云互联',
            'type'    => 'text',
            'dependency' => array('moefooter', '!=', ''),
            'class'    =>'compact',
        ), 
        array(
            'title'   => ' ',
            'desc'   => '请填写导航三链接',
            'id'      => 'url3',
            'default' => 'https://www.byvps.cn/',
            'type'    => 'text',
            'dependency' => array('moefooter', '!=', ''),
            'class'    =>'compact',
        ),
        array(
            'title'   => ' ',
            'desc'   => '客服一',
            'id'      => 'kefu1',
            'default' => '微信联系',
            'type'    => 'text',
            'dependency' => array('moefooter', '!=', ''),
            'class'    =>'compact',
        ),
        array(
            'title'   => ' ',
            'desc'   => '二维码图片链接',
            'id'      => 'kefuimg1',
            'default' => 'https://www.vxras.com/wp-content/uploads/2023/09/5E178C047F6F18B0A0B856EEA228ED90.jpg',
            'type'    => 'upload',
            'dependency' => array('moefooter', '!=', ''),
            'class'    =>'compact',
        ),
        array(
            'title'   => ' ',
            'desc'   => '客服二',
            'id'      => 'kefu2',
            'default' => 'QQ联系',
            'type'    => 'text',
            'dependency' => array('moefooter', '!=', ''),
            'class'    =>'compact',
        ),
        array(
            'title'   => ' ',
            'desc'   => '二维码图片链接',
            'id'      => 'kefuimg2',
            'default' => 'https://www.vxras.com/wp-content/uploads/2023/09/5E178C047F6F18B0A0B856EEA228ED90.jpg',
            'type'    => 'upload',
            'dependency' => array('moefooter', '!=', ''),
            'class'    =>'compact',
        ),
        array(
            'title'   => ' ',
            'desc'   => '客服三',
            'id'      => 'kefu3',
            'default' => '交流群',
            'type'    => 'text',
            'dependency' => array('moefooter', '!=', ''),
            'class'    =>'compact',
        ),
        array(
            'title'   => ' ',
            'desc'   => '图片链接',
            'id'      => 'kefuimg3',
            'default' => 'https://www.vxras.com/wp-content/uploads/2023/09/5E178C047F6F18B0A0B856EEA228ED90.jpg',
            'type'    => 'upload',
            'dependency' => array('moefooter', '!=', ''),
            'class'    =>'compact',
        ),
        array(
            'title'   => ' ',
            'desc'   => 'QQ',
            'id'      => 'footerqq',
            'default' => '82719519',
            'type'    => 'text',
            'dependency' => array('moefooter', '!=', ''),
            'class'    =>'compact',
        ),
        array(
            'title'   => ' ',
            'desc'   => '交流群',
            'id'      => 'footerqun',
            'default' => '783754655',
            'type'    => 'text',
            'dependency' => array('moefooter', '!=', ''),
            'class'    =>'compact',
        ),
        array(
            'title'   => ' ',
            'desc'   => '邮箱',
            'id'      => 'email',
            'default' => '82719519@qq.com',
            'type'    => 'text',
            'dependency' => array('moefooter', '!=', ''),
            'class'    =>'compact',
        ),
        array(
            'title'   => ' ',
            'desc'   => '备案号填在这里，支持自定义html显示在最下面',
            'id'      => 'footerzdy',
            'default' => '湘-ICPXXXXXXXX',
            'type'    => 'text',
            'dependency' => array('moefooter', '!=', ''),
            'class'    =>'compact',
        ),

      ),));